/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartworks;

import com.beust.jcommander.internal.Lists;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import org.testng.TestListenerAdapter;
import org.testng.TestNG;

/**
 *
 * @author Reece
 */
public class SmartWorksWindow extends javax.swing.JFrame 
{
    static String username = "";
    static String password = "";
    static String testcase = "";

    /**
     * Creates new form SmartWorksWindow
     */
    public SmartWorksWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jframe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Case = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        passWord = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jframe.setBackground(new java.awt.Color(63, 223, 238));
        jframe.setForeground(new java.awt.Color(93, 213, 241));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\SmartWorks\\thc.jpg")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(231, 61, 85));
        jPanel2.setForeground(new java.awt.Color(231, 61, 85));

        Case.addItem("Customer Setup");
        Case.addItem("Vending Collect");
        Case.addItem("Vending Trial");
        Case.addItem("Vending FBE");
        Case.addItem("Auxiliary Setup");

        jLabel4.setText("Test Case:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("USERNAME:");

        jLabel3.setText("PASSWORD:");

        userName.setToolTipText("");

        passWord.setToolTipText("");

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jframeLayout = new javax.swing.GroupLayout(jframe);
        jframe.setLayout(jframeLayout);
        jframeLayout.setHorizontalGroup(
            jframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeLayout.createSequentialGroup()
                .addGroup(jframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jframeLayout.createSequentialGroup()
                        .addGroup(jframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(passWord)))
                    .addGroup(jframeLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jframeLayout.setVerticalGroup(
            jframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jframe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jframe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      username = userName.getText();
        userName.setText(username);
        password = passWord.getText();
        passWord.setText(password);
        testcase = Arrays.toString(Case.getSelectedObjects());
        testcase = testcase.replace("[", "");
        testcase = testcase.replace("]", "");
        
        
        String str = testcase;
       switch(str)
       {
           case "Customer Setup":
               if(userName == null || userName.getText() == null || userName.getText().trim().length()==0)
                {
                    JOptionPane.showMessageDialog(userName, "Please enter Username");

                }
                    else if(passWord == null || passWord.getText() == null || passWord.getText().trim().length()==0)
                    {
                        JOptionPane.showMessageDialog(passWord, "Please enter Password");
                    }
               else
                    {
                        TestListenerAdapter cs = new TestListenerAdapter();
                        TestNG testng = new TestNG();
                        List<String> cssuites = Lists.newArrayList();
                        cssuites.add("C:\\SmartWorks\\SmartWorks\\test\\SmartWorks_Test.xml");//path to xml..
                        testng.setTestSuites(cssuites);
                        testng.run();
                    }
                break;
                
                case "Vending Collect":
                    if(userName == null || userName.getText() == null || userName.getText().trim().length()==0)
                    {
                        JOptionPane.showMessageDialog(userName, "Please enter Username");

                    }
                        else if(passWord == null || passWord.getText() == null || passWord.getText().trim().length()==0)
                        {
                            JOptionPane.showMessageDialog(passWord, "Please enter Password");
                        }
                    else
                        {
                            TestListenerAdapter vc = new TestListenerAdapter();
                            TestNG vencol = new TestNG();
                            List<String> vcsuites = Lists.newArrayList();
                            vcsuites.add("C:\\SmartWorks\\SmartWorks\\test\\SmartWorks_Vending_Collect.xml");//path to xml..
                            vencol.setTestSuites(vcsuites);
                            vencol.run();
                        }
                break;
                
                case "Vending Trial":
                    if(userName == null || userName.getText() == null || userName.getText().trim().length()==0)
                    {
                        JOptionPane.showMessageDialog(userName, "Please enter Username");

                    }
                        else if(passWord == null || passWord.getText() == null || passWord.getText().trim().length()==0)
                        {
                            JOptionPane.showMessageDialog(passWord, "Please enter Password");
                        }
                    else
                        {
                            TestListenerAdapter vt = new TestListenerAdapter();
                            TestNG venctri = new TestNG();
                            List<String> vtsuites = Lists.newArrayList();
                            vtsuites.add("C:\\SmartWorks\\SmartWorks\\test\\SmartWorks_Trial_Vending.xml");//path to xml..
                            venctri.setTestSuites(vtsuites);
                            venctri.run();
                        }
                break;
                
                case "Vending FBE":
                    if(userName == null || userName.getText() == null || userName.getText().trim().length()==0)
                    {
                        JOptionPane.showMessageDialog(userName, "Please enter Username");

                    }
                        else if(passWord == null || passWord.getText() == null || passWord.getText().trim().length()==0)
                        {
                            JOptionPane.showMessageDialog(passWord, "Please enter Password");
                        }
                        else
                            {
                              TestListenerAdapter fbe = new TestListenerAdapter();
                              TestNG venfbe = new TestNG();
                              List<String> vfbesuites = Lists.newArrayList();
                              vfbesuites.add("C:\\SmartWorks\\SmartWorks\\test\\SmartWorks_FBE_Vending.xml");//path to xml..
                              venfbe.setTestSuites(vfbesuites);
                              venfbe.run();
                            }
                break;
                
                case "Auxiliary Setup":
                    if(userName == null || userName.getText() == null || userName.getText().trim().length()==0)
                    {
                        JOptionPane.showMessageDialog(userName, "Please enter Username");

                    }
                        else if(passWord == null || passWord.getText() == null || passWord.getText().trim().length()==0)
                        {
                            JOptionPane.showMessageDialog(passWord, "Please enter Password");
                        }
                        else
                            {
                              TestListenerAdapter as = new TestListenerAdapter();
                              TestNG ass = new TestNG();
                              List<String> assuites = Lists.newArrayList();
                              assuites.add("C:\\SmartWorks\\SmartWorks\\test\\SmartWork_Auxiliaries.xml");//path to xml..
                              ass.setTestSuites(assuites);
                              ass.run();
                            }
                    break;
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartWorksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartWorksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartWorksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartWorksWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartWorksWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Case;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jframe;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextField passWord;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

}
